### ISSUE TITLE
commutative-0.0.1.2 still can't compile its test suite

### ISSUE THREAD

**Issue by peti** [athanclark/commutative#2]
Citing from http://hydra.cryp.to/build/1064721/log/raw:

~~~~
Preprocessing test suite 'spec' for commutative-0.0.1.2...

test/Main.hs:3:8:
    Could not find module ‘Data.CommutativeSpec’
    Perhaps you meant
      Data.Commutative (needs flag -package-key commutative-0.0.1.2@commu_2izDk5LxnBHIKrIV5HJpe1)
    Use -v to see a list of the files searched for.
~~~~~

**Comment by athanclark** [comment]
Was this built with `cabal-install`? Building in a sandbox works fine for me, as does `stack build`.

**Comment by peti** [comment]
This is built using the release tarball from Hackage with `cabal-install`.

**Comment by athanclark** [comment]
I was missing the `Other-Modules` stanza for the test suite. Version `0.0.1.3` has this fixed.
